version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Testtest
      POSTGRES_DB: BitcoinBot
    ports:
      - "5432:5432"